digitalbitbox/bitbox-base

armbian/base/build/customize-armbian-rockpro64.sh
Fixes crash on opening channels, patched upstream in:
https://github.com/lightningd/plugins/pull/21
=> armbian/base: Bump prometheus-lightningd.py to latest version

armbian/base/build/customize-armbian-rockpro64.sh
This is a customize script for the middleware. It does not include any nginx configurations yet and still statically chooses the rpc password and username. @hkjn gave me a tour of the cookie auth today, once that is merged, I'd like to include it as well.
=> Add middleware to Customize Script

armbian/base/build/customize-armbian-rockpro64.sh, armbian/base/scripts/startup-checks.sh
* bugfix: Wifi password build argument was not set correctly
* bugfix: startup-script did not recognize already set up ssd correctly
=> minor fixes

armbian/base/config/grafana/dashboard/grafana_bitbox_base.json
* lighter colors
* added mempool visualization: Mempool size by fee (sat/vbyte)
=> Grafana dashboard update

armbian/build.sh
We are using `rock64` so this would allow us to customize the board.
=> Can customize the BOARD

armbian/build.sh
non of the other options use quotations
FYI: have not yet tested this one!
=> Removes doublequotes from clean option, when action is update

Dockerfile
Fix Version and File Flag in docker run
=> Fix version and file flag in docker run

docs/about.md, docs/applications.md, docs/base-image.md, docs/contributing.md, docs/hardware.md, docs/middleware.md, docs/operating-system.md, docs/os/armbian-build.md, docs/support.md, docs/upgrade.md, docs/upgrade/concept.md
This pull request fixes 
* the navigation (os & base-image were identical)
* minor lint issues (whitespaces etc.)
=> Minor fixes & lint

middleware/src/middleware.go
Tiny Pull request to fix the formatting of the json tag in the SampleInfo struct.
=> Use proper json formatting in SampleInfo struct

Dockerfile, Makefile
@hkjn,
This PR achieve the following:
* Cleanup the docker image during `make clean`
* Make efficient use of docker cache system by building the tools inside the `Dockerfile` and the use of multi stage build
* `docker-build-go` is only building (no build if docker cache hit) and copying the build output to the host's mapped folder
This make sure that modifications only to tooling for example does not rebuild the middleware.
If no file changes then `docker-build-go` is near instantaneous.
=> Improve docker build and caching

tools/bbbsupervisor/bbbsupervisor.go
Like `logFollower`, a `prometheusFollower` has a basic `follow()`
method, and when called to follow, periodically queries a Prometheus
server for a particular expression.
This PR has no 3rd party dependencies.
=> tools/bbbsupervisor: Implement basic prometheusFollower (without 3rd party deps)

docs/os/armbian-build.md
See https://github.com/digitalbitbox/bitbox-base/issues/83 for context.
=> docs: Mention reported qemu issue

.dockerignore, .gitignore, Makefile, armbian/Makefile, armbian/mender-convert.sh, build/README.md, docs/index.md, docs/start.md, docs/start/build-process.md, provisioning/README.md, scripts/move-armbian-image.sh
Integration of Mender.io update management
* clone preliminary github repository
* integrate into build scripts / Makefiles
* documentation
=> Preliminary Mender update integration

middleware/src/handlers/handlers_test.go, middleware/src/middleware_test.go, middleware/src/noise/noise.go, middleware/src/noise/noise_test.go
Also cleanup some of the other test cases and fix two cases that were broken due to rebasing.
=> Make sure noise is initialized before attempting encryption

middleware/src/handlers/handlers.go
Events are now propagated to all connected clients. Incoming messages are processed in a separate goroutine.
=> Add support to send data to multiple connected clients at once

armbian/base/scripts/bbb-cmd.sh
**improve usb_flashdrive**
* rename 'usb_thumbdrive' to 'usb_flashdrive'
* recognize usb drives without partitions
* improve error messages
**imlement backup of Redis dbdump and hsm_secret**
* create / restore backup of Redis database file to /mnt/backup
* create / restore backup of '/mnt/ssd/bitcoin/.lightning/hsm_secret' into Redis key lightningd:hsm_secret
=> bbb-cmd: improve usb_flashdrive / add backup

armbian/base/customize-armbian-rockpro64.sh
* changes in customize build script
* adds additional dependency of python3-mako
=> update to c-lightning v0.7.2.1

armbian/base/scripts/bbb-cmd.sh
for consistency with bbbmiddleware
=> bbb-cmd: rename usb_flashdrive to flashdrive

armbian/base/scripts/prometheus-base.py
The Prometheus scraper for bitcoind reads the hostname and other metadata from configuration. Previously, this was achieved by sourcing configuration files, now the script reads directly from the central Redis configuration database.
=> switch prometheus-base.py to Redis

middleware/.golangci.yml, middleware/src/handlers/handlers.go, middleware/src/middleware.go, middleware/src/middleware_test.go, middleware/src/rpcmessages/rpcmessages.go, middleware/src/rpcserver/rpcserver.go, middleware/src/rpcserver/rpcserver_test.go
This adds the RPCs to the middleware needed to setup the Base in the App. In combination with https://github.com/digitalbitbox/bitbox-wallet-app/pull/506.
=> Middleware: Add RPCs needed for the base setup

tools/bbbsupervisor/bbbsupervisor.go
The supervisor previously paniced when e.g. a Prometheus query was unsuccessful. This panic did not get recovered, but is now. Errors and log messages are logged via the standard package 'log' for now.
=> Add supervisor error handling

armbian/base/config/templates/bitcoin.conf.template, armbian/base/scripts/bbb-config.sh, middleware/integration_test/bbb-config.sh
new command to configure bitcoind ibd over clearnet is:
```
bbb-config.sh set bitcoin_ibd_clearnet <true|false>
```
=> bbb-config: move 'bitcoin_ibd_clearnet' to 'set' section

tools/bbbsupervisor/bbbsupervisor.go
When the IBD is finished and the clearnet IBD key is set to 1 (IBD over clearnet) it is set back to 0 (IBD over Tor).
=> supervisor: add clearnet-ibd finished handling

armbian/base/scripts/bbb-cmd.sh, armbian/base/scripts/bbb-config.sh
Bash scripts `bbb-config.sh` and `bbb-cmd.sh` now write a defined error code to ErrOut before exiting with return code 1 on error.
See overview of error codes:
https://gist.github.com/Stadicus/6c9d186f78e86a4a3d682a24d008506e
This WARN message [here](https://github.com/digitalbitbox/bitbox-base/blob/d7a2133fb24d7815ee0091071e1fbdc8bf7ca375/armbian/base/scripts/bbb-cmd.sh#L325) does not need to abort the script and can be neglected for the moment.
=> scripts: add errorExit() and official error codes

armbian/base/scripts/prometheus-bitcoind.py
The metric bitcoin_tor_address returns the first 'localaddresses' address entry from bitcoind 'getnetworkinfo' query. Not bullet proof, but works in this configuration as we don't expect any other local addresses.
If Tor is not enabled for the Base, the scraper returns 'n/a'.
=> prometheus: add bitcoin_tor_address to bitcoin scraper

armbian/base/scripts/bbb-config.sh
Because:
* The settings bitcoin_ibd and bitcoin_ibd_clearnet were initially
handled like triggers (e.g. 'set bitcoin_ibd true')
* As the only valid values for both settings are 'set true' or
'set false', it is more consistent to 'enable' or 'disable' them.
* This also makes it easier to call them from the Middleware in a
way consistent with other calls.
This commit:
* moves the functionality 'bbb-config.sh set bitcoin_ibd true/false'
and 'bbb-config.sh set bitcoin_ibd_clearnet true/false' to the
'enable/disable' section
* keeps the bare skeleton of the old functions for compatibility,
marked as DEPRECATED, with the script calling itself again using
the new syntax
=> bbb-config: move bitcoin_ibd to enable/disable section

armbian/base/scripts/prometheus-base.py
https://github.com/shiftdevices/bitbox-base-internal/issues/284
Because:
* local IP address can change and needs to be updated frequently. It
makes sense to add it to the prometheus-base.py scraper, so that
this value becomes available in Prometheus, ready to be queried by
other programs.
This commit:
* extens the 'prometheus-base.py' scraper to add the ip_address to
the the base_system_info object
* always returns the IP address that is used to actively query
external addresses.
* the script connects to a dummy IP address (192.0.2.0) that is
reserved by IETF RFC 5737 for documentation purposes and should
be blocked by ISPs
https://datatracker.ietf.org/doc/rfc5737/
Output of scraper:
```
base_system_info{base_hostname="bitbox-base",base_ipaddress="192.168.1.161",base_version="0.0.3",build_ …
```
=> prometheus: add local ip address

middleware/src/middleware.go, middleware/src/middleware_test.go, middleware/src/redis/redis.go, middleware/src/rpcmessages/errorcodes.go, middleware/src/rpcmessages/rpcmessages.go, middleware/src/rpcserver/rpcserver_test.go
This PR implements Error Codes (based on #198) for the middleware RPCs.
=> Middleware: Error Codes implementation

middleware/src/rpcmessages/rpcmessages.go
In combination with https://github.com/digitalbitbox/bitbox-wallet-app/pull/588#pullrequestreview-302436217.
=> rpcmessages: update GetBaseInfoResponse with lower-case json names

Dockerfile, middleware/.golangci.yml, middleware/contrib/envinit.sh, middleware/src/handlers/handlers_test.go, middleware/src/handlers/websocket.go, middleware/src/middleware.go, middleware/src/noise/noise.go, middleware/src/prometheus/prometheus.go, middleware/src/redis/redis.go, middleware/src/util.go
Includes a bunch of small fixes that were caught by the new go linting tools.
=> Update Go version to 13.1 and Golangci Lint to 19.1

middleware/cmd/middleware/main.go
Use it with '-redismock true', default is 'false'.
=> Add Argument to mock running redis

armbian/base/scripts/systemd-update-checks.sh
In order to show a Update success/failure in the App, the Middleware needs to know if the update succeeded. This pull request implements IPC notification from update script to Middleware on success/failure
https://github.com/shiftdevices/bitbox-base-internal/issues/266
* the systemd-update-checks.sh script writes a success/failure msg
into the middleware-notification.pipe, encoded in JSON
* must be merged and is already tested with https://github.com/digitalbitbox/bitbox-base/pull/251
=> update: send ipc notification to middleware

armbian/base/scripts/prometheus-bitcoind.py
https://github.com/shiftdevices/bitbox-base-internal/issues/334
Because:
* The bitcoind scraper (prometheus-bitcoind.py) starts the Prometheus http server immediately, even if bitcoind is not ready yet.
* Metrics are then displayed as zero values, which are stored into the Prometheus time-series database.
* This leads to sudden drops in blockheight, verification process to zero on every reboot.
This commit:
* makes sure that the http server is only started after bitcoind RPCs are available
=> prometheus: prevent bitcoind zero values

middleware/cmd/middleware/main.go, middleware/go.sum, middleware/src/handlers/handlers.go, middleware/src/middleware.go, middleware/src/middleware_test.go, middleware/src/rpcmessages/errorcodes.go, middleware/src/rpcserver/rpcserver.go, middleware/src/rpcserver/rpcserver_test.go, middleware/src/system/system.go, middleware/src/system/system_test.go, middleware/src/util.go
The FinalizeSetupWizard RPC sets a Redis key indicating that the Base
has been setup, enables the Bitcoin services and starts the Bitcoin
services via the script added in #250.
=> add: FinalizeSetupWizard RPC

docs/applications/bitcoin-core.md, docs/applications/c-lightning.md, docs/applications/electrs.md, docs/applications/grafana.md, docs/os/armbian-build.md, docs/tinkering.md
this pull request fixes some broken links found manually after committing https://github.com/digitalbitbox/bitbox-base/pull/253, and also using brokenlinkcheck.com
=> docs: fix broken links

bin/go/README.md, bin/img-mender/README.md, docs/applications/bitcoin-core.md, docs/applications/c-lightning.md, docs/applications/electrs.md, docs/applications/prometheus.md, docs/applications/redis.md, docs/applications/tor.md, docs/customapps/additional-scripts.md, docs/customapps/bbb-cmd.md, docs/customapps/bbbconfgen.md, docs/hardware.md, docs/hardware/components.md, docs/networking.md, docs/operating-system.md, docs/os/armbian-build.md, docs/os/configuration.md, docs/os/os-faq.md, docs/os/security.md, docs/overview.md, docs/overview/releases.md, docs/tinkering.md, docs/tinkering/build-ondevice.md, docs/tinkering/overlayroot.md, docs/tinkering/ssh.md, docs/ui.md, docs/update/update-method.md, docs/update/update-notification.md, docs/update/update-unsigned.md
Add **Releases** page: point to this page from GitHub releases to explain the file types and how to verify releases.
**General update of technical docs**
Additional sections:
* additional scripts
* unsigned updates
* update notification
* build-ondevice
Updated:
* Operating System
* Applications
* Custom Applications
* README in /bin folders
=> update technical docs

docs/ui.md
fix broken link to digitalbitbox/bitbox-wallet-app after validation with online link checker
=> fix broken link to digitalbitbox/bitbox-wallet-app

middleware/src/middleware.go
Initial implementation of the heartbeat sent by the middleware to the HSM.
Sends the heartbeat every 5 seconds with `IDLE` and `" "` (stateCode=0, descriptionCode=0)
Tested this on an HSM with a screen without the rest of the Base hardware (no redis). 
@0xB10C Here are the protobuf message definitions for how the codes are enumerated: https://github.com/digitalbitbox/bitbox02-api-go/blob/master/api/firmware/messages/bitboxbase.proto
So we can just have two redis keys, `stateCode` and `descriptionCode` and each of them storing an int from the enum range in the proto file.
=> middleware-heartbeat: sends a heartbeat to the hsm every 5 seconds

middleware/src/rpcmessages/rpcmessages.go
Comes together with: https://github.com/digitalbitbox/bitbox-wallet-app/pull/746 on the App side
=> rpcmessages: harmonize fields and json format with App
