digitalbitbox/bitbox-base

armbian/build.sh

added a #Settings section into build.sh to allow easier adjustments of the VirtualBox settings (number of CPUs, memory)

build.sh: easier adjustment of VirtualBox settings

---

armbian/base/build/customize-armbian-rockpro64.sh

Configure the `avahi-daemon` to publish the hostname within the local network and make the device reachable, e.g. under `bitbox-base.local`

avahi-daemon: publish-workstation=yes

---

armbian/base/build/customize-armbian-rockpro64.sh
armbian/base/config/grafana/dashboard/grafana_bitbox_base.json

Extended Grafana dashboard with c-lightning measures:
* Node status info
* sync in % (dependency to upstream pull-request https://github.com/lightningd/plugins/pull/27, but not critical)
* Peers active / inactive
* Channels active / inactive
* Funds on-chain / in channels

Extend dashboard with c-lightning measures

---

armbian/base/build/customize-armbian-rockpro64.sh

Prevent the services to fill up the internal eMMC / sdcard when SSD is not mounted

must-mount-ssd

---

armbian/base/config/iptables/iptables.rules

This is a fairly restrictive networking config that disallows
all ingress and egress traffic apart from a known good set of
services. The functionality of the Base appears unharmed, with
the grafana dashboard loading fine, all services appearing to
continue running, no obvious errors and no blocked traffic
(which appears in `journalctl --all -f` logs) that seems unintentional.
This should be integrated into the systemd services to automatically
do `iptables-restore < <path to iptables.rules>` after the network
comes up and before any services are started.

armbian/base: Add basic iptables.rules config

---

armbian/base/build/customize-armbian-rockpro64.sh
armbian/base/scripts/set-bitcoin-network.sh

* configure middleware with configuration file (using environment variables)
* use `Wants=` instead of `Requires` in systemd to start the service in any case
* adjust `base-middleware.conf` when switching Bitcoin networks

set middleware config with config file

---

armbian/base/build/build.conf
armbian/base/build/customize-armbian-rockpro64.sh
armbian/base/scripts/autosetup-ssd.sh
armbian/base/scripts/startup-checks.sh

The bash script `storage-setup.sh` detects possible targets and can set them automatically (interactive or without prompt):
```
BitBox Base: Auto-Setup SSD
This script checks for potential storage targets and automates the setup process.
Use with caution, data on targets will be deleted.
Usage: ./storage-setup.sh <status|apply> [device] [--force]
Examples:
* ./storage-setup.sh status                 Get list of potential target devices in system
* ./storage-setup.sh apply /dev/sda         Set up specified device interactively
* ./storage-setup.sh apply auto             Detect device and set up interactively
* ./storage-setup.sh apply auto --force     WARNING! Execute only in well defined environments!
```
When building the image, the following can be specified:
* in …

autosetup-ssd.sh & build option

---

armbian/base/build/build.conf
armbian/base/build/customize-armbian-rockpro64.sh
armbian/build.sh

Various minor fixes and features adds
* freeze Armbian at latest stable release (sunxi-4.20)
* build option to manually set root password (development only)
* build option to configure default wifi network (needs additional hardware module)
* display build options (dedicated script function)

Wifi configuration on build & Armbian freeze

---

armbian/base/build/customize-armbian-rockpro64.sh

* changed general systemd targets to `network-online.target`
* added a delay before `bitcoind` start to allow Tor to create the SOCKS proxy
* added a delay after `bitcoind` to allow the .cookie file to be written reliably

Optimize systemd startup process

---

armbian/base/build/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/startup-checks.sh

* install `acl` (access control lists) to secure `/mnt/ssd/bitcoin/.bitcoin/.cookie` file to be created using `sysperms=1` and no world permissions (secured from users like "hdmi" outside group "bitcoin")
* electr: load blockchain data directly from the bitcoind directory (not via json-rpc)
* fix unbound variables in `bbb-config.sh`

Minor improvements / fixes

---

.travis.yml
Dockerfile
middleware/.golangci.yml
middleware/Makefile
middleware/scripts/ci.sh
scripts/travis-ci.sh

Travis CI now runs builds of the middleware and the bbbfancontrol. The travis job runs in its own docker container and runs golangci-lint according the specs defined in middleware/.golangci.yml .
I split the actual docker run into a separate file. When I ran the same lines directly from the script part of the travis.yml , the travis build would fail with the error: "docker: invalid reference format". Tips on how to fix this are welcome. 
The travis build will initially fail until the middleware sticks to the golangci style.

Add Travis CI with Dockerfile

---

middleware/cmd/middleware/main.go
middleware/src/middleware.go
middleware/src/system/system.go

All command line arguments are now passed to a separate data structure
inside its own package that only exposes the data with getter functions.
This commits also adds the network and electrs port command line
arguments.

Add environment package to track external configs

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/system/system.go

The desktop app needs to know about the network type and the electrs port such that it can create the correct entries in its backend configuration. This pull request adds a simple get handle that is able to return the json marshalled data of the Environment struct.

Add GetEnvHandler to send electrs port and network type

---

armbian/build.sh

In 24ae9acd, we added the `LIB_TAG=sunxi-4.20` build tag, which
checks out a specific git tag of the github.com/armbian/build repo.
This means that `git pull` won't work. From a clean checkout:
```
$ cd armbian && make
bash /home/user/src/hkjn.me/bitbox-base/armbian/build.sh build
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
git pull <remote> <branch>
Cleaning up by halting any running vagrant VMs..
==> default: VM not created. Moving on...
make: *** [Makefile:4: default] Error 1
$ echo $?
2
```

armbian: Fix broken build by removing 'git pull'

---

Makefile
middleware/Makefile

Before this change, there was some issue with dependencies
with the default `make` target for the Go tools.
Specifically, in `middleware/main.go` we import other packages:
```
github.com/digitalbitbox/bitbox-base/middleware/src
github.com/digitalbitbox/bitbox-base/middleware/src/handlers
```
The user who has checked out their own fork of the `bitbox-base`
repo might or might not have these packages under the expected path:
```
$GOPATH/src/github.com/digitalbitbox/bitbox-base/middleware/src/{,handlers}
```
A further improvement would be to either `go get` the dependencies we
need, or fail with a better error message, if we can detect this situation
reliably.
Since we have a dockerized build for the Go tools, let's use
that for the default `make` target. I've added a separate
`make …

Makefile: Use the dockerized build for Go tools by default

---

armbian/base/build/build.conf
armbian/base/build/customize-armbian-rockpro64.sh
armbian/base/scripts/systemd-startup-checks.sh
armbian/build.sh

Various minor configuration fixes:
* better, recursive ACL for directory `/mnt/ssd/bitcoin/.bitcoin`
* fix setting hardlinks for bbb-* scripts (now: symlinks)
* remove sha256sum display at end of build script, can take long time with multiple images
* use new [bitbox-base-deps](https://github.com/digitalbitbox/bitbox-base-deps) repository for prebuilt binaries
* by default, c-lightning is compiled during build, but can optionally be installed as package

Improved stability & faster build

---

armbian/build.sh

Minor change to fix missing `BOARD` argument in `build.sh`
Without it, the board variable is ignored, resulting in a interactive prompt to choose the board:
After the fix, the BOARD is recognized

Fix BOARD argument in build.sh

---

armbian/base/build/customize-armbian-rockpro64.sh

Looks like this line was accidentally commented out in
https://github.com/digitalbitbox/bitbox-base/pull/48#discussion-diff-292464056R505

armbian/base: Return accidentally commented-out line

---

Makefile
armbian/build.sh
docs/os/armbian-build.md
middleware/Makefile
scripts/travis-ci.sh

Note that we do not switch over Travis CI to use the dockerized build yet, since some issues remain:
* https://github.com/digitalbitbox/bitbox-base/issues/39#issuecomment-501343881
After this change, the default `make` command in the root of the repo (`make build-all`) uses Docker to build the Armbian image as well. (We already were building the Go services using Docker since ac5a3040.)

Dockerize armbian build

---

docs/os/build-details.md

This piece of documentation goes into a bit more depth about
how the Armbian build process works, specifically which scripts
copy which files from host -> overlay -> Armbian filesystem,
and which scripts have which responsibilities.
~_Edit:_ This PR doesn't directly depend on https://github.com/digitalbitbox/bitbox-base/pull/56, but it does describe the Armbian build process as being dockerized, so probably would make sense to merge that PR first.~

docs: Add build-details.md doc

---

middleware/src/system/system.go

The rpcpassword getter mistakenly returned the rpcuser. This is an embarassing regression. It would be nice, if the dockerfile would include regtest setups of c-lightning and bitcoind to check if the middleware is still capable of communicating / routing traffic with them.

Fix Regression in system.go

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go

The middleware package now communicates purely through a generic event interface with the handler. I thus removed a TODO that was created for this task. The event is then sent through a websocket connection to connected clients.

Make the websocket in the middleware just send json

---

docs/go-apps.md
docs/go/build.md
docs/go/middleware.md
docs/go/tools.md
docs/middleware.md
docs/os/build-details.md

Also move middleware.md into docs/go/ and add some minimal content to
the page.
Also add /docs/go/build.md with a description of the Go build process.
Also add /docs/go/tools.md doc with a minimal description of `bbbfancontrol`
and `bbbsupervisor`.
Also add link to Go docs from docs/os/build-details.md.

docs: Add top-level Go applications page

---

docs/about.md
docs/go/build.md
docs/index.md
docs/os/build-details.md

As an aside, we might want to set up some quick scraper as part of CI to check that there's no links that 404s, since checking manually might become cumbersome..

Fix some broken links, add Go applications to index.md

---

armbian/base/build/customize-armbian-rockpro64.sh
docs/applications/bitcoin-core.md

* get Bitcoin Core signing key from keyserver instead of downloading it directly
* make `bitcoind` listen over Tor directly
Built & tested on Alice

bitcoind: signing key & Tor listening

---

.gitignore
Makefile
armbian/Makefile
armbian/build.sh
build/README.md
middleware/Makefile
scripts/clean.sh
tools/bbbfancontrol/Makefile
tools/bbbsupervisor/Makefile

By adding a build/README.md file, we can guarantee that the build/
directory always will exist, so we no longer need the
`build-target-exists` make targets.
h/t @NicolasDorier, who had questions prompting us to rethink this
setup which led to this patch.
Instead just inline the command in the `Makefile`.

Simplify build rules

---

tools/Makefile
tools/bbbsupervisor/bbbsupervisor.go

With this change, we have no 3rd party dependencies remaining for
bbbsupervisor.go.
If we fail to start the `journalctl` command or receive any output
on stderr, we currently pass on the message and crash with non-success
exit status.
Also enable building bbbsupervisor in tools/Makefile.

tools/bbbsupervisor: Rework supervisor to avoid 3rd party deps

---

armbian/base/config/iptables/iptables.rules

I'm not sure why these ended up as commented out in aa44547af9679cfbdf7b945fc2093eeef2992da6, but it wasn't intentional, and the current state doesn't respond to `ping` since the packets end up being `DROP`'ed.

armbian/base: Allow ICMP/ping

---

armbian/Makefile
docs/base-image.md
docs/os/armbian-build.md
scripts/move-armbian-image.sh

This setup simplifies the build process, by making all build outputs
(whether intermediary like Go binaries or the final Armbian build
output) end up in build/.

armbian: Move .img to build/ after build is done

---

armbian/base/build/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/systemd-bitcoind-post.sh
armbian/base/scripts/systemd-electrs-start.sh
armbian/base/scripts/systemd-lightningd-post.sh

Configuration of `bitcoind` and `lightningd` to log to the systemd journal:
* run executable directly from the systemd unit file (not from a script)
* use option `printtoconsole` to log to stdout
* run as regular program (not `daemon`), otherwise `printtoconsole` is ignored
* run systemd unit as `Type=simple` due to not using the `daemon` option

Configure main apps to log to systemd journal

---

.circleci/config.yml

Please consider having an alternative CI, in case travis is down or slow.
In other projects CircleCI is starts and runs faster, but for bitbox-base it takes about the same amount.
example build with this PR's config
https://circleci.com/gh/thisconnect/bitbox-base/15

Setup CircleCI config

---

.gitignore
Makefile

Second attempt to make it easier to serve https://base.shiftcrypto.ch/ locally during development. (See https://github.com/digitalbitbox/bitbox-base/pull/37 for the first one.)
We no longer use Vagrant for builds, so the issues seen in #37 no longer should affect us.
We have another odd interaction however between the dockerized Armbian build process and Jekyll, where Jekyll appears to try to read a non-existing directory. In this change, we work around that issue by removing the parent directory from the build cache, and we also add a TODO to describe how this could be improved.

Makefile: Add docker-jekyll rule

---

armbian/base/build/customize-armbian-rockpro64.sh
armbian/base/scripts/systemd-lightningd-post.sh

Previously, the Armbian disk image was > 2 GB. Removing many unnecessary packages allowed to shrink the Armbian image by 50% to ~1 GB. As Mender uses compressed update images, the data to download for a full disk image update will be < 300 MB.
Includes minor improvements that popped up during testing:
* electrs: start binary directly from electrs.service
* c-lightning: add slight delay before setting group permissions on rpc

Downsize Armbian disk image to ~1 GB

---

.dockerignore

This directory is present if the user has run `make docker-jekyll`,
added in 5b3477c4, and can be multiple GB. Excluding it from Docker
builds speeds things up significantly.

.dockerignore: Also ignore _site/

---

Dockerfile
Makefile
docs/base-image.md

By using the same user inside the container as on the host, we avoid
issues with the host user lacking the privileges to e.g remove files
under `build/`, which are bind-mounted from the host into the container.
Before this change, those files would run as the super-user (`id -u` of
`0`), which caused the issues mentioned above, specifically on Gitlab,
where subsequent test runners would find themselves unable to clean up
the `build/` artifacts from prior builds.
The unfortunate edge case here is for users that (wisely!) require
`sudo` to run `docker` commands, there is no way for the `Makefile`
to deduce what their non-privileged user's id is. Those users
need to either deal with the super-user (id `0`, commonly `root`)
owning the files under `build/`, or to explicitly specify their …

Use host user for Docker builds

---

Dockerfile
Makefile
docs/base-image.md

This reverts commit 0e5efd51eb8b082a2a014a7fe28f18d60504bdb5.
We noticed that 0e5efd51 introduced a regression, which made it
necessary for users who require `sudo` for their `docker` commands
to also specify `BUILDER_UID=$(id -u)` explicitly on the commandline.
(We were aware that this parameter was needed if users wanted to run
`docker` commands with `sudo`, and they also wanted the `build/`
directory to be owned by their non-privileged user, but it was not known
or intended that the build wouldn't work at all with `sudo make`.)

Revert "Use host user for Docker builds (#98)"

---

armbian/base/build/customize-armbian-rockpro64.sh
armbian/base/config/grafana/dashboard/grafana_bitbox_base.json
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/systemd-startup-checks.sh

Minor improvements
* disable UART serical console output, as a preparation for HSM connectivity
* disable Armbian ZRAM swapfile and replace it with custom swapfile on SSD (includes additional Grafana charts)
* allow `bbb-config.sh exec bitcoind_reindex` to wipe chainstate and reindex downloaded blocks
* use standard `network-manager` instead of hardcoded files
* remove unnecessary Avahi service announcements
* general cleanup of customize script

General stability improvements and scripting cleanup

---

armbian/Makefile
armbian/base/build/build.conf
armbian/base/build/customize-armbian-rockpro64.sh
armbian/base/build/customize-image.sh
armbian/base/config/grafana/dashboard/grafana_bitbox_base.json
armbian/base/config/iptables/iptables.rules
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/prometheus-bitcoind.py
armbian/base/scripts/systemd-startup-checks.sh
armbian/build.sh
armbian/mender-convert.sh
scripts/move-armbian-image.sh

**overlayroot**
This pull request mainly improves the stability of the operating system by
* using the latest build of Armbian Ubuntu 18.04 (Bionic Beaver)
* optionally enabling `overlayroot` that mounts the rootfs as read-only and adds an ephemeral tmpfs overlay filesystem on top
With `overlayroot`, corrupting the rootfs should be almost impossible and it also extends the lifetime of the eMMC significantly.
**make ondevice**
The configuration script now supports multiple Linux distributions Armbian (Debian Stretch or Buster, Ubuntu Bionic) or Ayufancan, and can be run directly on the device to configure a BitBox Base.
```
git clone https://github.com/digitalbitbox/bitbox-base.git
cd bitbox-base/armbian/
nano base/build/build.conf
make build-ondevice
```

Move to Ubuntu 18.04 and read-only rootfs

---

armbian/base/scripts/prometheus-bitcoind.py

queries bitcoin-cli getblockchaininfo and stores the header field in 'bitcoin_headers'

add 'bitcoin_headers' to Prometheus Bitcoin scraper

---

middleware/src/handlers/handlers.go
middleware/src/handlers/handlers_test.go
middleware/src/handlers/websocket.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go

Each websocket connection now spawns a new gob encoded rpc server.
Protobuf encoding is dropped for this purpose.
The rpc server package creates read and write channels that are wrapped into a io.ReadWriteCloser interface. This interface is implemented in the rpcConn struct of the server package. The websocket loop in the handlers package now uses these rpcConn channels to read and write websocket messages.
When a new websocket connection is created in the wshandler in the handlers package, a new rpc server and subsequent websocket read and write loop is spawned. The rpcserver's write channel is also passed into a map of all clients and can then receive notification events again through the listenEvents() function.
The available rpc calls are implemented in the rpcserver.go file. …

middleware: Implement GOB RPC server

---

middleware/.gitignore
middleware/Makefile
middleware/README.md
middleware/integration_test/docker-compose.yml

Add a docker-compose file in the integration_test directory. `docker-compose` will then run, bitcoind, electrs and two instances of lightningd. It can be controlled with the `make regtest-up` and `make regtest-down` target.

Docker regtest

---

middleware/cmd/middleware/main.go
middleware/src/handlers/handlers.go
middleware/src/handlers/websocket.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/prometheus/prometheus.go
middleware/src/rpcserver/rpcserver.go
middleware/src/system/system.go
middleware/src/system/system_test.go

During initial blockchain download we do not want to hit bitcoind with direct rpc calls, instead call prometheus, which schedules the calls at healthy intervals. Add a rpc call that returns the syncing progress as given by bitcoin core and the total number of blocks and headers synced.
Improve channel close handling in the websocket loop

Middleware: Add prometheus package to track bitcoin verification progress 

---

.gitignore
armbian/base/build/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/bbb-systemctl.sh
armbian/base/scripts/systemd-bitcoind-post.sh
docs/go/middleware.md
docs/start/build-process.md
middleware/.gitignore
middleware/Makefile
middleware/README.md
middleware/base-middleware.service

Renaming gives consistency over all our own tools, like bbbsupervisor or bbbfancontrol

rename base-middleware to bbbmiddleware

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcserver/rpcserver.go

Add an argument to the ResyncBitcoin rpc endpoint in the rpcserver package to allow the client caller to choose between executing a full bitcoin resync, and wiping the chanstate and reindex again from existing blocks.

Middleware: Bitcoin resync and bitcoin reindex option

---

armbian/base/scripts/bbb-config.sh

The command 'bbb-config.sh exec bitcoin_resync' deletes the following directories:
* /mnt/ssd/bitcoin/.bitcoin/blocks
* /mnt/ssd/bitcoin/.bitcoin/chainstate
* /mnt/ssd/electrs/db
It removes the trigger file /data/triggers/bitcoind_fully_synced and restarts bitcoind. The dbcache needs to be set to a higher value manually, or by the supervisor.

add 'exec bitcoin_resync' option to bbb-config.sh

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go

The rpcmessage.go file now specifies how to structure the incoming arguments, the outgoing reply and the notifications of rpccalls.

Middleware: Add RPCMessage file to centralize definition of rpc messages

---

armbian/base/scripts/systemd-startup-checks.sh

The hostname is not stored directly in /etc/hostname, which is a symlink to /data/network/hostname. As the /data directory is prepared on first boot, the hostname is still set to 'localhost' and must be set manually, otherwise it is not correctly announced to the network.

set hostname on first boot

---

docs/_config.yml

remove local Jekyll 'theme' to prevent GitHub page build warning

remove local 'theme' to prevent GitHub page build warning

---

middleware/src/handlers/websocket.go
middleware/src/rpcserver/rpcserver.go

Remove Pairing Verification from Websocket Loop. The Verification Is now done directly in the noise handshake. If a verification call should be available later, make it available through a rpc call.
Document RPCConn roles as io.ReadWriteCloser.

Websocket cleanup

---

armbian/base/config/iptables/iptables.rules
armbian/base/customize-armbian-rockpro64.sh

Two minor fixes:
* execute systemd-electrs-startpre.sh as root 
* allow incoming TCP port 50002 for electrs in iptables by default  
Enabling / disabling electrs port should later become part of the configuration management.

Minor fixes

---

middleware/README.md
middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/prometheus/prometheus.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go

The middleware polls its rpc connections to lightningd, bitcoind and prometheus every 5 seconds. If new data was received, the corresponding struct is updated and a notification that a new rpc call is sent to the connected wallet app.
Add new tests for the rpc methods and update the Readme to the new rpc event loop.

Rpc event queue

---

.dockerignore
Dockerfile
Makefile
middleware/Makefile
tools/bbbfancontrol/Makefile
tools/bbbsupervisor/Makefile

Restructuring of repo directories, especially combining `/build` and `/provisioning` into the various `/bin/*` directories, broke the build process. Fixed by this pull request.

Adjust Docker Go build for ./bin/go destination

---

armbian/base/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-cmd.sh
armbian/base/scripts/bbb-config.sh

Extend `bbb-config.sh` with function to execute commands within `overlayroot-chroot`, e.g.
* `root_pw`: set root / base user password
* `root_pwlogin': enable / disable password login for 'root' user, both locally and for ssh
Add 'bbb-cmd.sh' as system commands repository, providing operating system-level commands to the command line and the middleware.
```
BitBox Base: system commands repository
usage: bbb-cmd.sh [--version] [--help] <command>
possible commands:
bitcoin_reindex   wipes UTXO set and validates existing blocks
bitcoin_resync    re-download and validate all blocks
base_restart      restarts the node
base_shutdown     shuts down the node
```

Extend config scripts for middleware

---

armbian/base/scripts/bbb-cmd.sh

Builds on top of pr https://github.com/digitalbitbox/bitbox-base/pull/141 and adds the commands mount a USB thumbdrive on `/mnt/backup`.
Thumbdrive detection uses several checks (e.g. must be <= 64GB) and drive is mounted with safe constraints (e.g. don't allow executable binaries or `suid` flags on the drive). 
```console
$ ./bbb-cmd.sh usb_thumbdrive check
/dev/sda1
$ ./bbb-cmd.sh usb_thumbdrive mount /dev/sda1
USB_THUMBDRIVE MOUNT: mounted /dev/sda1 to /mnt/backup
$ ./bbb-cmd.sh usb_thumbdrive mount /dev/sda1
mount: /mnt/backup: /dev/sda1 already mounted on /mnt/backup.
$ ./bbb-cmd.sh usb_thumbdrive unmount
USB_THUMBDRIVE UNMOUNT: /mnt/backup unmounted.
$ ./bbb-cmd.sh usb_thumbdrive unmount
USB_THUMBDRIVE UNMOUNT: no drive mounted at /mnt/backup
```

bbb-cmd.sh: check / mount / unmount USB drive for backup

---

armbian/armbian-build.sh
armbian/base/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-config.sh

Due to recent changes in Armbian Docker build process, this pull-request 
* add the `BUILD_MINIMAL=yes` argument
* installs `curl` for the BitBox Base image
Before moving the final disk image, the number of images available in the target directory is checked and expected to equal 1.

Fix Armbian Docker build

---

tools/bbbsupervisor/Gopkg.lock
tools/bbbsupervisor/Gopkg.toml
tools/bbbsupervisor/bbbsupervisor.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/LICENSE
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/internal/commandinfo.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/conn.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/doc.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/go16.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/go17.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/go18.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/log.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/pool.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/pool17.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/pubsub.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/redis.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/reply.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/scan.go
tools/bbbsupervisor/vendor/github.com/gomodule/redigo/redis/script.go

The `bbbsupervisor` needs to be able to access the central configuration management, to get information, but also to update data on events. This PR adds Redis connectivity and provides example code for SET and GET. Unused code is commented and can be un-commented when needed.   
The commit 64f994d introduces a dependency on [redigo/redis](https://github.com/gomodule/redigo) which is already used in `bbbconfgen`.

Supervisor: Add Redis connectivity and examples for SET and GET

---

armbian/base/config/redis/factorysettings.txt
armbian/base/config/redis/redis-local.conf
armbian/base/config/redis/redis.service
armbian/base/customize-armbian-rockpro64.sh
armbian/base/scripts/redis-pipe.sh

Add Redis to the Armbian build process. It is installed, configured and set up as a systemd unit. Initial configuration is mass-imported from factorysettings.txt
This is the prerequisite to move the configuration management consistently into Redis, which is not yet implemented.

Add Redis for configuration management

---

middleware/.golangci.yml
middleware/cmd/middleware/main.go
middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go
middleware/src/system/system.go
middleware/src/system/system_test.go

**WIP**: First version to gather feedback. Code builds, but I have no BBBase to run it yet.
This PR adds

Middleware: Add Flashdrive, Backup and Restore RPCs

---

middleware/src/rpcmessages/rpcmessages.go

This adds an ErrorResponse struct used to idicate if an RPC call was successful or not. It can be embedded into other RPC responses that return values. In any case the ErrorResponse should be checked first, so that, if an error is returned, we ignore everything else in the response.

Add ErrorResponse

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go

This PR adds two dummy RPCs to authenticate and change the password. This shall only be used for testing and development. 
See https://github.com/digitalbitbox/bitbox-base/pull/164#issuecomment-526148566 for current behavior.

Add dummy RPCs to Authenticate and ChangePassword

---

armbian/base/scripts/bbb-cmd.sh
middleware/integration_test/bbb-cmd.sh
middleware/integration_test/bbb-config.sh

Add mock `bbb-cmd.sh` and `bbb-config.sh` scripts in `/middleware/integration_test` to enable the Middleware to call these scripts in a development environment, without actually doing anything to the system.
All validation checks have been preserved.

add mock shell scripts for integration test

---

middleware/src/middleware.go

The `bbb-cmd.sh` methods to reindex and resync where changed in https://github.com/digitalbitbox/bitbox-base/pull/165. This PR restores interoperability between the middleware and the `bbb-cmd.sh` script.

Middleware: update to current bbb-cmd resync|reindex methods

---

armbian/Makefile
armbian/base/config/redis/factorysettings.txt
armbian/base/config/templates/bashrc-custom.template
armbian/base/config/templates/bbbmiddleware.conf.template
armbian/base/config/templates/bitcoin.conf.template
armbian/base/config/templates/electrs.conf.template
armbian/base/config/templates/lightningd.conf.template
armbian/base/customize-armbian-rockpro64.sh
armbian/base/rootfs/etc/systemd/system/bbbmiddleware.service
armbian/base/rootfs/etc/systemd/system/bitcoind.service
armbian/base/rootfs/etc/systemd/system/electrs.service
armbian/base/scripts/bbb-cmd.sh
armbian/base/scripts/bitcoind-rpcauth.py
armbian/base/scripts/include/redis.sh.inc
armbian/base/scripts/systemd-bbbmiddleware-startpre.sh
armbian/base/scripts/systemd-bitcoind-startpost.sh
armbian/base/scripts/systemd-bitcoind-startpre.sh
armbian/base/scripts/systemd-electrs-startpre.sh
armbian/base/scripts/systemd-lightningd-startpre.sh
armbian/base/scripts/systemd-startup-checks.sh

This pull requests adds the recommended **rpcauth** methods for services to authenticate when using the bitcoind JSON RPC interface.
From the bitcoind help:
> `Username and HMAC-SHA-256 hashed password for JSON-RPC connections. The field <userpw> comes in the format: <USERNAME>:<SALT>$<HASH>. A canonical python script is included in share/rpcauth. The client then connects normally using the rpcuser=<USERNAME>/rpcpassword=<PASSWORD> pair of arguments. This option can be specified multiple times`
The rpcauth.py script from bitcoin repository to generate unique but persistent rpcauth credentials for bitcoind is added and extended to store the credentials directly in Redis.
To ensure unique credentials, the bitcoind-startpre script calls the command 'bbb-cmd.sh bitcoind refresh_rpcauth' if no …

bitcoind-rpcauth: script and service configuration

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go

This PR adds RPCs to enable/disable various Tor settings.
| RPC                 	        | Input         	        | Output        	        |
|---------------------	        |---------------	        |---------------	        |
| EnableTor           	        | `enable bool` 	| ErrorResponse 	|
| EnableClearnetIBD   	| `enable bool` 	| ErrorResponse 	|
| EnableTorMiddleware 	| `enable bool` 	| ErrorResponse 	|
| EnableTorElectrs    	| `enable bool` 	| ErrorResponse 	|
| EnableTorSSH        	| `enable bool` 	| ErrorResponse 	|

Middleware: Add Tor RPCs

---

middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver_test.go

To be in sync with the rpcmessages.go in the bitbox-wallet-app a
Error() string method is added to the ErrorResponse. Additionally the
ErrorResponse in GetHostnameResponse is unembedded to separate
namespaces more clearly.
https://github.com/digitalbitbox/bitbox-wallet-app/pull/506/commits/788e92fed16b7f157597829e2f2f1c0f6a4ba839

middleware: Add Error() to ErrorResponse

---

armbian/base/scripts/bbb-config.sh

According to IETF RFC 952 (https://tools.ietf.org/html/rfc952),
A "name" (Net, Host, Gateway, or Domain name) is a text string up to
24 characters drawn from the alphabet (A-Z), digits (0-9), minus sign (-),
and period (.). Note that periods are only allowed when they serve to
delimit components of "domain style names". No blank or space characters
are permitted as part of a name. No distinction is made between upper and
lower case. The first character must be an alpha character. The last
character must not be a minus sign or period.
Using the following regex to validate hostname before change:
^[a-z][a-z0-9-]{0,22}[a-z0-9]$

bbb-config: valdiate hostname using regex

---

middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcserver/rpcserver_test.go

The middleware hostname restrictions are updated to a subset of the specifyed valid hostnames in IETF RFC 952. In conjunction with https://github.com/digitalbitbox/bitbox-base/pull/186.

middleware: Update hostname restrictions

---

.gitignore
armbian/mender-convert.sh
contrib/cleanup-loop-devices.sh

I experience issues with many leftover loop devices on Ubuntu during after
the build process, causing builds to fail the next time.
As a workaround, the 'mender-convert.sh' script checks if the following
file is present and if so, calls the script contrib/cleanup-loop-devices.sh
```
armbian/.cleanup-loop-devices
```
This file is added as an exception to .gitignore

Cleanup loop devices during build

---

middleware/src/middleware.go

https://github.com/digitalbitbox/bitbox-base/pull/190 changes the method used to modify the `bitcoin_ibd_clearnet` setting from `enable/disable` to `set true/false` in the `bbb-config.sh` script. This is adopted here.
This PR should only be merged together with #190 and #187.

middleware: Update EnableClearnetIBD to changes in bbb-config.sh

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go

This PR implements following RPCs:
| RPC                | Input                 | Output                 |                  
|--------------------|-----------------------|-----------------------|
| ShutdownBase         | `dummyArg bool`  | ErrorResponse |
| RebootBase    | `dummyArg bool`  | ErrorResponse |

middleware: Add ShutdownBase and RebootBase RPCs

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go

This PR adds the following RPCs
| RPC                | Input                 | Output                 |                  
|--------------------|-----------------------|-----------------------|
| EnableRootLogin    |`enable bool`| ErrorResponse                                       |
| SetRootPassword    | `SetRootPasswordArgs`              | ErrorResponse                               |
The SetRootPassword RPC allows only passwords with a length greater or equal to 8 chars. The rune length is counted, so that Unicode symbols as e.g. `₿` don't count as multiple chars. See https://play.golang.org/p/yw6Adi167tk.

middelware: Add EnableRootLogin and SetRootPassword RPCs

---

armbian/base/config/redis/factorysettings.txt
armbian/base/customize-armbian-rockpro64.sh
armbian/base/scripts/autosetup-ssd.sh
armbian/base/scripts/systemd-startup-checks.sh

If a factory new BitBox Base is started the first time, with an empty SSD and a backup USB flashdrive plugged in, the flashdrive could be mounted at `/mnt/ssd` which is wrong.
Added some checks to only mount a drive with at least 400 GB as SSD (either external or internal is ok).
Additional fix: disable `serial-getty@ttyFIQ0` service that tries to activate non-existing serial console and causes a boot delay.

Prevent flashdrive to mount as /mnt/ssd

---

middleware/cmd/middleware/main.go
middleware/src/handlers/handlers.go
middleware/src/handlers/handlers_test.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/redis/redis.go
middleware/src/redis/redis_mock.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go

This PR adds the GetBaseVersion RPC. Additionally a Redis mock is introduced to enable unit tests on RPCs that GET or SET redis values.

Middleware: Add GetBaseVersion RPC

---

armbian/base/rootfs/etc/systemd/system/bitcoind.service
armbian/base/scripts/autosetup-ssd.sh
armbian/base/scripts/bbb-cmd.sh
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/bbb-systemctl.sh
armbian/base/scripts/include/errorExit.sh.inc
armbian/base/scripts/include/redis.sh.inc
armbian/base/scripts/systemd-bbbmiddleware-startpre.sh
armbian/base/scripts/systemd-bitcoind-startpost.sh
armbian/base/scripts/systemd-bitcoind-startpre.sh
armbian/base/scripts/systemd-electrs-startpre.sh
armbian/base/scripts/systemd-lightningd-startpost.sh
armbian/base/scripts/systemd-lightningd-startpre.sh
armbian/base/scripts/systemd-startup-checks.sh
armbian/base/scripts/systemd-update-checks.sh

all scripts have been cleaned up with shellcheck, unnecessary parts are removed and all aborts are handled with an error code.
The following new error codes are introduced:
generic
* SCRIPT_INVALID_ARG
ssd autosetup
* SSDSETUP_NO_TARGET
* SSDSETUP_TOO_MANY_TARGETS
* SSDSETUP_ABORTED_MANUALLY
lightningd / electrs
* BITCOIND_DEPENDENCY_NOT_ACTIVE
* BITCOIND_IN_IBD
bbb-systemctl.sh
* SYSTEMD_NOT_ALL_SERVICES_RUNNING
systemd-bitcoin-startpre.sh
* BITCOIND_DIRECTORY_NOT_ACCESSIBLE
redis.sh.inc
* REDIS_REQUIRED_BUT_NOT_RUNNING
systemd-startup-checks.sh
* SSD_NOT_MOUNTED
systemd-update-checks.sh
* MENDER_UPDATE_SYSCONFIG_FAILED

scripts: cleanup / add error codes

---

armbian/base/config/redis/factorysettings.txt
armbian/base/config/templates/iptables.rules.template
armbian/base/customize-armbian-rockpro64.sh
armbian/base/rootfs/etc/systemd/system/iptables-restore.service
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/systemd-iptables-restore.sh
armbian/mender-convert.sh

To avoid permissive iptables rules, the various configurations (esp. `tor:base:enabled` and `bitcoind:ibd-clearnet`) include or exclude certain rules when recreating the file `iptables.rules` from the template `iptables.rules.template`.
The build script and especially `bbb-config.sh` is extended to recreate and activate these rules by triggering the `iptables-restore.service` via systemd. This service no longer calls `/sbin/iptables-restore` directly but the script `systemd-iptables-restore.sh` that first flushes existing iptables rules.
Minor fix: also cleanup loop devices before mender-convert if trigger file is present (not just after).

iptables: dynamic config from template

---

armbian/base/config/redis/factorysettings.txt
armbian/base/config/templates/bitcoin.conf.template
armbian/base/scripts/systemd-startup-checks.sh

This setting instructs bitcoind to create new files (e.g. blocks and indices)
with system default permissions, instead of umask 077 (-rwx------).
It has been removed in error, but is needed for members of the bitcoin group
like electrs to have access to the blockchain data.
Access Control Lists (ACL) have also been added to control the default
permissions (set on startup with 'setfacl').

bitcoind: add 'sysperms=1' to config

---

armbian/base/config/redis/factorysettings.txt
armbian/base/config/templates/torrc.template
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/include/updateTorOnions.sh.inc
armbian/base/scripts/systemd-update-checks.sh

https://github.com/shiftdevices/bitbox-base-internal/issues/281
Because:
* Redis is the central configuration store, so the .onion addresses
of the hidden services of the Middleware, SSH, Electrs and Lighting
should be readily available there.
* Hidden service names are harmonized (e.g. electrum --> electrs) to
avoid confusion when referring to them on os-level / Redis / RPC
* The 'bbb-config get' command is no longer necessary, as its only
purpose was to fetch the onion addresses.
This commit:
* adds uninitialized Redis keys (e.g. tor:ssh:onion = xxx) for onion
addresses to the Redis factory settings
* harmonizes Tor hidden service names
* adds the function 'updateTorOnions()' as an include which is
called when enabling/disabling Tor or individual services
* this include is also called …

tor: add .onion to Redis / harmonize service names

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go

This commit uses the new ToggleSetting type to handle enabling or
disabling Base settings that have binary options.
This is for two reasons:
1. All parameters used in rpc calls should come from rpcmessages.go as discussed with @TheCharlatan 
2. Simplify middleware methods so there is no need for global
"enable/disable" variables and checking within each method call

middleware: handle binary setting calls with rpcmessage, not bool

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go
middleware/src/util.go

The middleware calls the bbb-cmd script with `check` `mount` and `unmount` for flashdrive operations. These fuctions were avaliable as RPCs, but are now included in the Backup and Restore sysconfig RPCs. This is done to minimize the amount of RPC calls and traffic, which might need to be send over Tor.
Removed are following RPCs:
- `MountFlashdrive`
- `UnmountFlashdrive`

Middleware: Include Flashdrive methods in Backup/Restore Sysconfig

---

middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver_test.go
middleware/src/util.go

Originally, the rpc parameter for all `Enable*` type calls was a `bool` that wasn't typed in `rpcmessages.go`
Later changed this to `"enable"`/`"disable"` strings required by the `bbb-config.sh` script on the base.
As there are only two options, this change avoids passing around unnecessary strings and instead typing the bool as `type ToggleSetting bool` in `rpcmessages.go`

middleware: change ToggleSetting rpc message from string to bool

---

middleware/src/middleware.go

RebootBase previously ran `base reboot` which is not a valid argument for the `bbb-cmd.sh` script. `base restart` is defined in `bbb-cmd.sh`.

change: RebootBase to run `base restart` and not `base reboot`.

---

middleware/src/rpcmessages/rpcmessages.go

I found the logging output for the print `ErrorResponse` uninformative and not well formatted when dealing with Errors in the logs. The Error() method is changed to print just `ErrorResponse: Success: true` when there is no Error. If an Error occurs the Success, Code and Message values printed in multiple lines. This should increased readability in the logs.
potential problem: If `Success` is incorrectly set to `true`, the message and code are not printed. This case should however be covered by unit tests for the RPC call.

refactor: ErrorResponse Error() method

---

middleware/cmd/middleware/main.go
middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/system/system.go
middleware/src/system/system_test.go

The Middleware needs an unauthenticated endpoint providing the
Middleware version. This Endpoint is added and reachable under
`http://<ip>:8845/version`
This is a replacement for #224.

Middleware: add /version endpoint 

---

middleware/src/middleware.go
middleware/src/rpcmessages/errorcodes.go
middleware/src/util.go

The RestartBase RPC and the ShutdownBase RPC should both return a response to the calling App before the shutdown is started. The previously used os.exec's `CombineOutput` waited for the script to complete and forking in the shell script did not resolve this.
The RPCs now execute the reboot/shutdown with a delay of <s>10 seconds</s> 5 seconds. The middlware responds to the App prior to the shutdown/reboot.

change: Restart & ShutdownBase without bbb-cmd.sh

---

middleware/cmd/middleware/main.go
middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/prometheus/prometheus.go
middleware/src/prometheus/queries.go
middleware/src/redis/keys.go
middleware/src/redis/redis.go
middleware/src/redis/redis_mock.go
middleware/src/rpcmessages/errorcodes.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go
middleware/src/system/system.go
middleware/src/system/system_test.go
middleware/src/util.go

The GetBaseInfo RPC provides information about the Base, which is displayed in the app's 'Base management' section. The RPCs `GetHostname` and `GetBaseVersion` are included in `GetBaseInfo`.
This PR includes placeholder values for:
- the current Base system status
- the Middleware's hidden service tor port
This PR does not include a unit test for `GetBaseInfo`, because a Prometheus mock is needed first.
I'll keep track of both, the placeholders (https://github.com/shiftdevices/bitbox-base-internal/issues/292) and unit tests (https://github.com/shiftdevices/bitbox-base-internal/issues/274) in a separate issues.

middleware: add first version of GetBaseInfo RPC

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go
middleware/src/util.go

Each rpc call's arguments should now be inside a struct such that they are easily extensible for additional fields, like an authentication cookie.
I had to add a couple of global variables to the middleware and rpcserver tests and subsequently removed the globals check in golangci. No globals in actual source files are in my opinion something that can be enforced by proper review.

RPC messages: move toggle setting to its own struct

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/prometheus/queries.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go
middleware/src/util.go

This commit adds a first version of the GetServiceInfo RPC.
The RPC returns information about services such as bitcoind, electrs and lightningd. Information includes for example the current block height or the count of connected peers.
The App should call this RPC once it receives a notification that the serviceInfo in the middleware has changed.
This RPC will likely be extended with additional information in the future.

Middleware: add first version of GetServiceInfo RPC

---

armbian/base/config/mender/mender.conf
armbian/base/config/redis/factorysettings.txt
armbian/base/config/templates/mender.conf.template
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/systemd-update-checks.sh

Because:
* Power users and developers should be able to run firmware images
built by themselves, independently from a Shift signature
This commit:
* introduces Redis key 'base:update:allow-unsigned' with default 0
* replaces the static /etc/mender/mender.conf file with a template
* adds the bbb-config.sh command 'enable/disable unsigned_updates'
* restores this setting on update

allow unsigned firmware upgrades

---

README.md
armbian/base/rootfs/etc/grafana/dashboards/grafana_bitbox_base.json
armbian/base/scripts/systemd-startup-checks.sh
armbian/base/scripts/systemd-update-checks.sh
docs/customapps/helper-scripts.md
docs/hardware/components.md
docs/os/upgrade.md
docs/overview.md
docs/overview/architecture.md
middleware/src/rpcmessages/errorcodes.go
middleware/src/rpcserver/rpcserver.go

To avoid confusion, the software running on the HSM is called 'firmware' and the Armbian operating system is called 'Base image'.
Addresses https://github.com/digitalbitbox/bitbox-base/pull/235#issuecomment-547012303
This commit
* replaces 'firmware' throughout the project where used wrongly.

wording: use 'Base image' instead of 'firmware'

---

middleware/src/util.go

This commit improves the response parsing of the flashdrive check
script call. On a responses with multiple lines a warning is logged.
On a response with no lines returns an ErrorResponse with a code of
ErrorUnexpected is returned. The flash drive name is now the last
line of the script output.
fixes https://github.com/shiftdevices/bitbox-base-internal/issues/297

Middleware: refactor improve get flashdrive name

---

armbian/base/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-config.sh
docs/applications/redis.md
docs/customapps/helper-scripts.md
docs/os/configuration.md
middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/middleware_test.go
middleware/src/rpcmessages/errorcodes.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/mocks/Middleware.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go

When restructuring and renaming some password, minor inconsistencies have been introduced. 
This harmonizes bbb-config.sh and the Go Middelware RPC. No RPCs are renamed, changes are Middleware --> Scripts only.

Password settings: harmonize script and RPCs

---

middleware/cmd/middleware/main.go
middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/redis/redis_mock.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/mocks/Middleware.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go
middleware/src/system/system.go
middleware/src/util.go
middleware/src/util/semver/semver.go

This adds a periodic check for firmware updates to the middleware.
If an update is available, a the middleware sends a notification.
The App can get more information about the update by calling the
IsBaseUpdateAvailable RPC, which returns a boolean indicating if
an update is available and information about the update.
The App should call `IsBaseUpdateAvailable` after the connection is
established.

Middleware: add Base firmware update check and notification

---

armbian/base/scripts/bbb-cmd.sh
armbian/base/scripts/systemd-update-checks.sh

Implements shiftdevices/bitbox-base-internal#308
**Add 'reset' features for authentication**
* Users need to be able to reset various aspects of the Base config.
* With `bbb-cmd.sh reset <auth|config|image|ssd>` different components can be reset to factory settings.
* When run manually, user needs to confirm the reset by typing `YES`. For non-interactive usage, the flag `--assume-yes` can be used.
The commit
* adds the overall framework for all 'reset' commands, without adding the specific functionality.
* Implements the first reset command `bbb-cmd.sh reset auth`
**Check reset trigger / token on flashdrive when booting**
* User must be able to reset a forgotten password.
* The App is of not much use, because the user can no longer access the Base using the App.
* On boot, the Base checks …

Add factory reset framework and implement authentication reset

---

middleware/cmd/middleware/main.go
middleware/src/ipcnotification/ipcnotification.go
middleware/src/middleware.go
middleware/src/system/system.go
middleware/src/system/system_test.go

This defines IPC notifications and adds a IPC notification reader,
which creates and opens a named pipe. Other processes, for example
shell or python scripts, can write notifications into the named pipe.
Notifications are sent in a JSON encoded string. The protocol in
version 1 requires notifications to have a version, topic and a
payload. Notifications can have a maximum length of 4096-1 byte.
Can be tested with:
```shell
echo '{"version": 1, "topic": "sampletopic", "payload": {"testInt":123,"testString": "string", "testBool": true}}' >> /tmp/middleware-notification.pipe
```

add: read IPC notifications from a named pipe

---

middleware/src/handlers/handlers.go
middleware/src/ipcnotification/payloads.go
middleware/src/middleware.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/util.go

Events passed from the Middleware to the handlers are now typed. The type `Event` now includes a boolean which indicates if the event should be queued until a client (App in our case) is available.
Handling for the `mender-update` notification is add, that is send by a shell script after the mender update commit finishes.
For testing:
```
echo '{"version": 1, "topic": "mender-update", "payload": {"success": true}}' >> /tmp/middleware-notification.pipe
echo '{"version": 1, "topic": "mender-update", "payload": {"success": false}}' >> /tmp/middleware-notification.pipe
```

Middleware: handle `mender-update` notification and queue if no client connected

---

armbian/base/build.conf
armbian/base/config/redis/factorysettings.txt
armbian/base/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/bbb-systemctl.sh
armbian/base/scripts/include/redis.sh.inc
armbian/base/scripts/systemd-update-checks.sh

Currently, all services are enabled and as soon as the BitBoxBase has power and network it will start syncing over Tor.
As we give the user different options during the Setup Wizard, services should not start before that.
This pull-request...
* adds the build option BASE_ENABLE_BITCOIN_SERVICES (default: false)
* does not enable bitcoind, lightningd and electrs systemd units during the build process
* introduces the Redis key base:bitcoind-services:enabled
* adds the command 'bbb-config.sh enable/disable bitcoin-services' to configure systemd and set the Redis key
* script 'systemd-update-check.sh' checks the Redis key on boot and enables the services if -eq 1 (the are not disabled otherwise)

enable Bitcoin services only after setup

---

armbian/base/config/templates/iptables.rules.template
armbian/base/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-cmd.sh
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/bbb-systemctl.sh

* bbb-cmd: unmount /mnt/backup before mounting
* mDNS: loosen iptables rules
* bbb-config: config grafana web also in overlayroot
* c-lightning: update to 0.7.3, solves a build issue when run on the device itself
* bbb-systemctl: when enabling bitcoin services, check if bitcoind in ibd mode, and don't start lightningd and electrs if true
See additional details in individual commits

collection of minor bash-script fixes 

---

armbian/base/config/templates/bbbmiddleware.conf.template
armbian/base/rootfs/etc/systemd/system/bbbmiddleware.service
middleware/README.md
middleware/cmd/middleware/main.go
middleware/src/handlers/handlers_test.go
middleware/src/middleware_test.go
middleware/src/rpcserver/rpcserver_test.go
middleware/src/system/system.go
middleware/src/system/system_test.go

The bitcoin and lightning rpc command line arguments for the middleware
were originally added to get some sample information and serve as
guidance on how to architecture the middleware. These direct methods to
lightning and bitcoind have since been deprecated, meaning the command
line arguments are also no longer needed.
This also removes the configuration from the systemd config templates
and the arguments from the systemd unit.
There are probably more occasions of the bitcoin and lightning rpc environment variables left to be cleaned up. Can you have a quick look at that @Stadicus?
Addresses https://github.com/shiftdevices/bitbox-base-internal/issues/332

Deprecate old command line arguments of the middleware

---

armbian/armbian-build.sh
armbian/base/customize-armbian-rockpro64.sh
armbian/base/rootfs/etc/systemd/system/startup-after-redis.service
armbian/base/scripts/prometheus-base.py
armbian/base/scripts/systemd-bbbmiddleware-startpre.sh
armbian/base/scripts/systemd-bitcoind-startpre.sh
armbian/base/scripts/systemd-startup-after-redis.sh
armbian/base/scripts/systemd-startup-checks.sh
armbian/base/scripts/systemd-update-checks.sh
middleware/Makefile
tools/bbbconfgen/Makefile
tools/bbbfancontrol/Makefile
tools/bbbsupervisor/Makefile

This pull request updates the build method to run the configuration script directly on a preinstalled Linux distribution. It's used mainly for testing of non-Armbian distributions.
**compile Go: use build instead of install in Docker**
https://github.com/shiftdevices/bitbox-base-internal/issues/326
Because:
* When cross-compiling the Go tools inside Docker, with the command
'docker install', the binaries are put into the directory
$GOPATH/bin/linux_arm64
* One goal is to run installation (incl. Go compilation) directly on
the ARM device, to support other distributions. When not cross-
compiling, the binaries are put into $GOPATH/bin/, failing the
make process.
This commit:
* uses 'go build' instead of 'go install' to always put the binaries
directly in the source directory and copy them …

update 'build-ondevice' make target

---

armbian/mender-convert.sh

https://github.com/shiftdevices/bitbox-base-internal/issues/263
https://github.com/shiftdevices/bitbox-base-signing/pull/1
When signing official releases, the uncompressed 8 GB Base image is cumbersome to process in Tails.
This pull request extends the build process to provide a compressed Base image named as `BitBoxBase-vX.X.X-RockPro64.tar.gz`

build: create Base image tarball

---

armbian/base/customize-armbian-rockpro64.sh

Related to https://github.com/digitalbitbox/bitbox-base/pull/255
After removing the necessity of /etc/bbbmiddleware/bbbmiddleware.conf, the build script must no longer import it as a template.
This commit:
* updates the broken build script

build: don't use bbbmiddleware.conf

---

armbian/base/scripts/bbb-cmd.sh

Because:
* Currently, the device (e.g. /dev/sdc1) needs to be provided to mount a backup flashdrive with 'flashdrive mount'.
* This info is available with 'flashdrive check'.
This commit:
* allows calling 'flashdrive mount' without argument and implicitely gets the information from 'flashdrive check'. This method still exits the command if any issue occurs with the correct error message.
* fixes error handling when mountpoint is already is in use and unmounts the usb drive first.

bbb-cmd: improve 'flashdrive mount'

---

armbian/base/config/templates/bbbmiddleware.conf.template
armbian/base/customize-armbian-rockpro64.sh

related to https://github.com/digitalbitbox/bitbox-base/pull/255
Because:
* The bbbmiddleware.conf.template and the created file are used by many scripts.
* It was removed in pr255, which breaks both build and operations.
This commit:
* adds an empty bbbmiddleware.conf.template that can be recreated at will, sourced from systemd as environment file etc. without breaking the configuration.
Future configuration can be added here again.

creating empty bbbmiddleware.conf

---

middleware/src/rpcserver/rpcserver.go

The rpc server did not check for a jwt in the current implementation
of EnableSSHPasswordLogin

jwtAuthentication: add token validation to EnableSSHPasswordLogin

---

middleware/src/middleware.go
middleware/src/prometheus/queries.go
middleware/src/redis/keys.go
middleware/src/rpcmessages/rpcmessages.go

This is the second iteration of GetBaseInfo. 
- change: merge OnionPort & LocalPort into one
This change merges the MiddlewareLocalPort and MiddlewareOnionPort
from the GetBaseInfoResponse into one MiddlewarePort, since they are
the same for now.
- change: only return Onion if Tor is enabled
This change leaves the MiddlewareTorOnion emtpy ("") if Tor is not
enabled on the Base. This helps showing the correct values in the
node management.
- add: active lightning channels to BaseInfo
This adds the number of active lightning channels to the GetBaseInfo-
Response.
- add: isSSHPasswordLoginEnabled bool to BaseInfo
This adds a boolean indicating if SSH password login is enabled to
the GetBaseInfoResponse.

Middleware: update GetBaseInfo 

---

armbian/base/scripts/bbb-cmd.sh
armbian/base/scripts/bbb-config.sh

Using the method `${VAR^^}` to set variables to uppercase is only supported from BASH 4.0 on. Running the regtest environment on Macs leads to script errors.
This commit:
* Makes sure all arguments are initialized like `VAR="${1:-}"`
* Uses POSIX-compatible 'tr' syntax to set variables to uppercase:
`VAR="$(tr '[:lower:]' '[:upper:]' <<< "${VAR}")"`

scripts: use POSIX-compatible uppercase method

---

armbian/base/config/redis/factorysettings.txt
armbian/base/scripts/bbb-config.sh

The Redis key 'base:bitcoind-services:enabled' was set after enabling the bitcoin-related services after the Setup Wizard. It was never checked anywhere else, though, all scripts are using 'base:setup' to decide whether to start these services.
This commit:
* removes key 'base:bitcoind-services:enabled'
* sets the key 'base:setup' to 1 also after manually enabling the bitcoin-related services with 'bbb-config.sh enable bitcoin-services' to ensure the services are started after IBD
* if the sync method should be changed after that (tor/clearnet/resync ect...), this can be triggered from the app.

scripts: remove base:bitcoind-services:enabled

---

armbian/base/scripts/systemd-startup-after-redis.sh
armbian/base/scripts/systemd-update-checks.sh

In the update image, bitcoin-related services are disabled. They are started after boot to check if all services are working correctly, but aren't enabled. The effect is that everything runs fine, until after the next reboot when bitcoind, lightningd and electrs do not start.
Services should always be enabled on update, and no check for the finished Setup Wizard is necessary, as it is not a feasible scenario that the Base is updated without being set up first.
This commit:
* enables the bitcoin-related services during the update process
* adds a check on every boot if Redis key 'base:setup' is 1 and
enables the services if needed

update: re-enable bitcoin services

---

armbian/base/build.conf
armbian/base/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-config.sh

**build: lock users & unlock on loginpw/rootlogin**
On building the Base image, the pw for users 'root' and 'base' are set with a random password, but all images will have the same. This is why the users need to be locked on build. When setting a custom system password in the BitBoxApp advanced settings, the password is set and the user 'base' is unlocked
* lock user 'root' when building the Base image
* lock user 'base' on building, but only if no `BASE_LOGINPW` has been set
* unlocks 'base' user when calling `bbb-config.sh enable loginpw`
* unlocks/locks 'root' user when calling `bbb-config.sh enable/disable rootlogin`
**ssh keys: add flag to build without keys**
When shipping BitBoxBase devices, no development SSH keys must be included. On build, the configuration option …

Lock users on build, don't add SSH keys by default

---

middleware/src/middleware.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/util.go

- Move active lightning channels from base to service info
- return 0 instead of error for some unavailable values
Because:
* Certain values such as lightning and electrs blocks will not be
available until bitcoin is fully synced. We still want to return
useful information during the syncing process.
* Zeroes in this case make sense
This commit:
* return a 0 for bitcoindBlocks, bitcoindHeaders, lightningdBlocks,
lightningActiveChannels, and electrsBlocks instead of an error
when these are not available

Service info fix

---

armbian/armbian-build.sh
armbian/base/build.conf
armbian/base/customize-armbian-rockpro64.sh

When building the BitBoxBase on an existing device, binary Go application dependencies might not have been built from source.
This pull-request allows to download the binary dependencies from GitHub as one tarball and make them available in bin/go. 
A new CONFIG section on top of the customize-armbian script specifies all application and binary dependencies versions.
* collects all application VERSION variables in a CONFIG section
* retrieves all Go binaries in a single command
* removes individual binary handling for custom Go apps
* removes build option BASE_BUILD_LIGHTNINGD (must always build from source)
Tested both in Armbian build system and on a vanilla Ayufan distribution (`make build-ondevice`).

build: cleanup binary dependencies

---

armbian/base/scripts/systemd-startup-after-redis.sh
armbian/base/scripts/systemd-startup-checks.sh

Because:
* The startup checks try to copy the static mender.conf file, that
has been removed in commit 79f6bd9f50e92f79d4f3c3cc2dd7bd47f7b13df9
This commit:
* moves these checks to the startup-after-redis script to generate
the mender.conf dynamically from the template

scripts: fix startup check mender.conf

---

armbian/base/scripts/prometheus-base.py

Because:
* The Base scraper for Prometheus reads two files:
- /sys/class/thermal/thermal_zone0/temp
- /sys/class/hwmon/hwmon0/pwm1
* If these are not present, the whole scraper fails.
This commit:
* wraps the reading of these files in try/except

prometheus-base: catch err if pwm1 not present

---

armbian/base/scripts/bbb-config.sh
middleware/src/middleware.go
middleware/src/rpcmessages/errorcodes.go

fixes https://github.com/shiftdevices/bitbox-base-internal/issues/355
The script bbb-config.sh expects Tor to be enabled when enabling the BITCOIN_IBD_CLEARNET option, and give the error ENABLE_CLEARNETIBD_TOR_ALREADY_DISABLED otherwise.
This should not really be a prerequisite and Tor can just be enabled if necessary.
This commit:
* makes the command BITCOIN_IBD_CLEARNET enable Tor if necessary
* Remove Go error ErrorEnableClearnetIBDTorAlreadyDisabled

enable Tor for BITCOIN_IBD_CLEARNET if necessary

---

Makefile
armbian/Makefile
armbian/armbian-build.sh
armbian/base/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/systemd-startup-checks.sh

Armbian changed the build process and renamed their git branches. This pull-request fixes this, addresses some minor build improvements and extends the top-most `make` command.
**build fixes / improvements**
* switches to Armbian branch 'legacy' (fix)
* sets the .autosetup-ssd trigger as default and commits it also in overlayroot (bug)
* prompts for 'build.conf' when building ondevice
* optionally, run cleanup-loop-devices.sh before compilation
* source errorExit include in systemd-startup-checks.sh (bug)
**Makefile changes**
* extends 'make build-all' to include Mender postprocessing
* renames 'update' to 'update-all' and includes Mender postprocessing

Fix / improve build process

---

middleware/src/hsm/hsm.go

There are blocking operations like verifying the pairing code on the
HSM, which should not timeout in 5s.
A proper fix is to have the HSM timeout itself by default after a
defined period, and have the client read timeout be larger than this.
For now we just increase the timeout to give enough time hopefully.

middleware/hsm: increase read timeout

---

armbian/base/scripts/create-presync-archive.sh

The creation of a presync archive should be easily reproducible, with the right files included (and excluded) from the archive.
This pull request adds 'create-presync-archive.sh' to be run directly on the BitBoxBase.

script: create-presync-archive.sh

---

armbian/base/config/redis/factorysettings.txt
armbian/base/config/templates/bbbmiddleware.conf.template
armbian/base/rootfs/etc/systemd/system/bbbmiddleware.service

The HSM serial port (default: `/dev/ttyS2`) needs to be passed by command line to the bbbmiddleware.  This is what the `/etc/bbbmiddleware/bbbmiddleware.conf` is for, so the configuration is stored in Redis and loaded as environment variable into systemd unit.
This pull request
* adds Redis keys `bbbmiddleware:datadir` and `bbbmiddleware:hsmserialport`
* adds these to the config template `bbbmiddleware.conf.template`
* loads them as env variables and passes them to the binary as cli arguments in the systemd unit
Tested successfully in new BitBoxBase image build.

bbbmiddleware: add hsmserialport to config

---

middleware/src/hsm/hsm.go

The serial package's max timeout is silently capped at 25.5s:
https://github.com/tarm/serial/blob/98f6abe2eb07edd42f6dfa2a934aea469acc29b7/serial.go#L158
We need longer for the blocking HSM operations to be able to finish.
We might add a shorter timeout and a repeater in the future, to still
abort after a (long) time, but unless we fully go async, all those
solutions are suboptimal.

middleware/hsm: use blocking call over timeout (for now)

---

armbian/armbian-build.sh
armbian/mender-convert.sh

I don't believe anyone needs full history of the armbian and
mender-convert repos. Last commit + branch should be enough.
One can always "git clone ..." manually with custom options.
This produces the same result without issues.

armbian: check out only one branch/commit

---

Dockerfile

This is used to build tools/... and probably middleware/... I believe.
I suggest subscribing to https://groups.google.com/group/golang-announce to stay up to date with the regular and out of schedule releases.

docker: update dockerfile to use latest go1.13.4

---

armbian/base/customize-armbian-rockpro64.sh

related: https://github.com/digitalbitbox/bitbox-base/pull/294
Only the repository version with the release tag is necessary, not all branches and histories.
This commit:
* clones the tag directly with `git clone --depth=1 -b v${LIGHTNING_VERSION}`

lightningd: clone release tag directly

---

armbian/base/scripts/bbb-cmd.sh

fixes https://github.com/shiftdevices/bitbox-base-internal/issues/354
When resetting the authentication Redis keys, the Middleware needs to be restarted to update its internal state
This commit:
* restarts the bbbmiddleware.service incl. error handling

bbb-cmd: restart bbbmiddleware after auth reset

---

middleware/cmd/middleware/main.go
middleware/src/configuration/configuration.go
middleware/src/configuration/configuration_test.go
middleware/src/handlers/handlers_test.go
middleware/src/middleware_test.go

This PR consists of two commits. 
The first fixes two switched parameters to the `NewConfiguration()` factory function. A Middleware without the fix the tires to HTTP GET update information from the `middlewarePort` (8845) and delivered the `imageUpdateInfoURL` as Middleware port to the App. This resulted in the App not getting notified about new updates. The bug was introduced in #285.
The second commit makes the `NewConfiguration()`function more developer friendly by requiring a struct with named fields as argument rather than just a sequence of (unnamed) parameters. For this an extra `Args` struct with public fields is used, which can be filled from the `main` package. The fields of the `Configuration` struct remain private and only accessible via Getters, because they should not be …

Middleware: Fix and mitigate switched parameters in Configuration factory function 

---

middleware/src/middleware.go
middleware/src/util.go

Adds error logging to each field in `BaseInfo` and `ServiceInfo` so that we can clearly tell which query had failed.

base/service-info: add error logging to each info field

---

middleware/src/middleware.go
middleware/src/util.go

This commit:
Adds the `setHSMConfig()` function to call the HSM API's
`BitBoxBaseSetConfig()` on middleware startup and when the Base hostname
is changed using an RPC.
The IP and hostname are fetched from redis and prometheus respectively
whenever `setHSMConfig` is called.
For `statusLedMode` and `statusScreenMode` we currently use the default
`LED_ALWAYS `and `SCREEN_ALWAYS` until we have redis config for those values.

hsm-config: set hsm config on middleware start and SetHostname

---

middleware/src/handlers/handlers.go
middleware/src/rpcserver/rpcserver.go
middleware/src/rpcserver/rpcserver_test.go

The Golang [rpc package] requires a special schematic for methods. Otherwise the package prints a warning which has been confused with an error in the past (https://github.com/shiftdevices/bitbox-base-internal/issues/354). The warning was logged when the BitBoxApp connected to the Middleware.
```console
rpc.Register: method "Serve" has 1 input parameters; needs exactly three
```
This adds dummy parameters to the Serve() method to remove the warning.
[rpc package]: https://golang.org/pkg/net/rpc/
fixes https://github.com/shiftdevices/bitbox-base-internal/issues/356

Middleware: remove warning on RPC server Serve()

---

middleware/src/middleware.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/rpcserver.go
middleware/src/util.go

The RPCServer logged the same "sent reply" message for each RPC response. The output contained values, but no field labels for the values.
This adds the name of the RPC to the response log and prints the responses with field names. This should make the Middleware logs more accessible for debugging.
Example before:
```log
2019/12/06 17:51:04 sent reply &{ErrorResponse: Success: true\n 606941 606941 0.9999953681135885 9 false 606941 0 606942}:
```
Example after:
```log
2019/12/06 18:00:10 RPCServer sent reply for the "GetServiceInfo" RPC: &{ErrorResponse:ErrorResponse:{Success: true} BitcoindBlocks:606951 BitcoindHeaders:606951 BitcoindVerificationProgress:0.9999994641028246 BitcoindPeers:8 BitcoindIBD:false LightningdBlocks:606950 LightningActiveChannels:0 ElectrsBlocks:606951}
```
fixes …

Middleware: cleanup RPCServer log messages for RPC replies

---

armbian/base/customize-armbian-rockpro64.sh

fixes https://github.com/shiftdevices/bitbox-base-internal/issues/369
Currently, we update the HSM firmware together with the Base image. For the Middleware to update the HSM, the specific version of the HSM firmware needs to be included in the disk image.
This issue extends the build script to provide a specific release version in the disk image. The version is specified like `HSM_VERSION='4.3.0'`, that is then used to create the valid download URI like this:
```
https://github.com/digitalbitbox/bitbox02-firmware/releases/download/firmware-bitboxbase%2Fv4.3.0/firmware-bitboxbase.v4.3.0.signed.bin
```
It is important, that the `tag` of the release always follows this syntax: `firmware-bitboxbase/v4.3.0`
and the file is named like `firmware-bitboxbase.v4.3.0.signed.bin`.
The release binary …

HSM: add firmware to Base image

---

armbian/base/rootfs/etc/grafana/dashboards/grafana_bitbox_base.json
armbian/base/scripts/prometheus-base.py

fixes https://github.com/shiftdevices/bitbox-base-internal/issues/370
Prometheus should log the availability of public internet without
leaking privacy information.
This pull requests queries an external host with a lot of general
traffic, Cloudflare, over Tor:
```
curl --socks5-hostname localhost:9050 1.1.1.1
```
If Tor is not active, it's impossible to ping an external host without
revealing the own ip address, but the solution can just "mingle in the
crowd", e.g. by `ping`ing Cloudflare, which should not be suspicious.
```
ping -c 1 1.1.1.1
```
These queries are run regularly from `prometheus-base.py`, so that the
result is collected by Prometheus and stored in its time-series database.
This helps with analyzing/debugging incidents, as the public network
availability can also be …

Prometheus: log public network availability

---

armbian/base/build.conf
armbian/base/customize-armbian-rockpro64.sh

addresses https://github.com/digitalbitbox/bitbox-base/issues/291
The various build options make it difficult to spot if in total everyting is set correctly to build a production image. By adding the binary option `BASE_PRODUCTION_IMAGE` to build a PRODUCTION or DEV image, and setting all options to safe production defaults, configuration errors can be minimized.
This commit:
* adds the build option `BASE_PRODUCTION_IMAGE`
* sets all defaults to production values that can only be overwritten
if `BASE_PRODUCTION_IMAGE=='false'`

build: switch to build production image

---

docs/overview/diy.md
docs/overview/releases.md

related: https://github.com/digitalbitbox/bitbox-base/issues/290
Because:
* It was not mentioned that only eMMC is supported and booting from a
Mender MicroSD card does not work
This commit:
* adds this note about only supporting eMMC
* generally improves DIY and Releases docs

docs: improve DIY and Releases docs

---

armbian/base/scripts/systemd-update-checks.sh

fixes https://github.com/shiftdevices/bitbox-base-internal/issues/375
The user-set system password is not persisted on update. Even if SSH password login is enabled, the user is not able to log in without setting the password through the BitBoxApp again.
As this is a rather unsafe setting, it is not persisted on update. The goal is to use SSH keys, which can safely be persisted and don't need the `sshpwlogign` option to be enabled at all.
As of now, the Redis key `base:sshd:passwordlogin` is not set back to `0`, so the App still shows the setting as enabled, although it is not.
This commit:
* sets the Redis key `base:sshd:passwordlogin` back to `0` and `base:sshd:rootlogin` to `no` to reflect the real configuration.

update: reset 'sshpwlogin' on success

---

armbian/base/scripts/bbb-cmd.sh
docs/customapps/bbb-cmd.md
docs/os/configuration.md

The command `bbb-cmd.sh flashdrive unmount` is in some instances (e.g. help text and documentation) mistyped as `umount`.
This commit
* fixes all `umount` typos

bbb-cmd: fix 'umount' typo instead of 'unmount'

---

armbian/armbian-build.sh
armbian/base/customize-armbian-rockpro64.sh
armbian/mender-convert.sh

If SUDO_USER is not set during a build, an error "unbound variable" is shown.

fix: set a default for the SUDO_USER variable

---

armbian/mender-convert.sh

fixes https://github.com/digitalbitbox/bitbox-base/issues/327
Major changes in the mendersoftware/mender-convert repository broke the build post-processing. No need to immediately update our scripts, so pinning the version 1.2.2 (Dec 2019) is fine for now.
This commit
* clones the tag '1.2.2' from the public mender-convert repo

build: pin mender-convert version to 1.2.2

---

middleware/src/handlers/handlers.go
middleware/src/middleware.go
middleware/src/rpcmessages/rpcmessages.go
middleware/src/rpcserver/mocks/Middleware.go
middleware/src/rpcserver/rpcserver.go
middleware/src/util.go

This pr addresses https://github.com/shiftdevices/bitbox-base-internal/issues/395 by adding a GetServiceStatus method to the rpc server as specified in the issue. It also adds a utility function to check whether the services are active in systemd.

middleware: Add unauthenticated endpoint for service status

---

armbian/base/customize-armbian-rockpro64.sh
armbian/base/scripts/bbb-cmd.sh
armbian/base/scripts/bbb-config.sh
armbian/base/scripts/include/exec_overlayroot.sh.inc
armbian/base/scripts/include/generateConfig.sh.inc
docs/applications/nginx.md
docs/applications/redis.md

* add `bash-completion` package on build
* allow `overlayroot-chroot` commands to fail with error logging
* use `apt-get` instead of `apt` in scripts (https://github.com/shiftdevices/bitbox-base-internal/issues/405)
* use `apt-get purge` instead of `apt-get remove` to also remove config files (related to https://github.com/shiftdevices/bitbox-base-internal/issues/404)
See commits for additional details.

Minor improvements

---

README.md
bin/go/README.md
bin/img-armbian/README.md
bin/img-mender/README.md
docs/CNAME
docs/README.md
tools/bbbsupervisor/README.md

This project is inactive and unmaintained at the moment.
security@shiftcrypto.ch sometimes receive "vulnerability repots"
against base.shiftcrypto.ch. However harmless those reports have been
so far, there may be real security issues with hosting an unmaintained
website on a shiftcrypto.ch subdomain.
The commit is the first step in migrating from base.shiftcrypto.ch to
digitalbitbox.github.io/bitbox-base. Once this is submitted, next steps
are:
1. Check https://github.com/digitalbitbox/bitbox-base/settings/pages
and ensure settings are correct.
2. Change DNS replacing base.shiftcrypto CNAME with something that
points to a Shift Crypto web frontend.
3. Make the web frontend redirect base.shiftcrypto.ch/... to
digitalbitbox.github.io/bitbox-base/...
4. Update all existing links on …

docs: drop custom domain
